### ISSUE TITLE
Uncaught TypeError: lastFocusable is undefined

### ISSUE THREAD

**Issue by sebastienserre** [vincedubroeucq/kawi#6]
Hello,

When I visit the customizer in the Appearance menu, the "Layout" section disappear and the console says `Uncaught TypeError: lastFocusable is undefined` on `kawi/js.main.min.js`
![js-error](https://user-images.githubusercontent.com/3902621/96501290-78e6b000-1250-11eb-9c56-a146c790fe39.png)

**Comment by vincedubroeucq** [comment]
Hey ! Thanks for pointing out the issue !
The "Layout" section is only present when the page displayed is the blog or has a sidebar, since its settings controls the blog posts layout and sidebar position, so that's normal.

However the Javascript error is a problem.
I cannot reproduce the issue though.
Does the error appear on specific situation ? Can you help me reproduce it ?
Thanks a lot !

**Comment by vincedubroeucq** [comment]
Hey !
I could not reproduce the error, this is strange.
I wrapped the JS code triggering the error in an `if` statement to prevent it.
That should do the trick
